default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['POSTGRES_HOST']  %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  database: <%= ENV['POSTGRES_DB'] %>

development:
  <<: *default

test:
  <<: *default
  database: mhc_test

production:
  <<: *default

staging:
  <<: *default
